language: java

install:
 - gradle assemble
 - sudo ./gradlew assemble

before_install:
 - chmod +x gradlew

script:
 - gradle check
 - ./gradlew check

android:
 components:
 licenses:
   - android-sdk-preview-license-.+
   - android-sdk-license-.+
  

after_success:
  - bash <(curl -s https://codecov.io/bash)
